config/routes.rb
Rails.application.routes.draw do
  resources :examples

  resources :stories
  root 'examples#index'

end

app/models/example.rb
class Example
	include MongoMapper::Document

  key :nounOne, String, :required => true
  key :nounTwo, String, :required => true
  key :nounThree, String, :required => true
  key :nounFour, String, :required => true
  key :verbOne, String, :required => true
  key :verbTwo, String, :required => true
  key :verbThree, String, :required => true
  key :verbFour, String, :required => true
  key :verbFive, String, :required => true
  key :adjectiveOne, String, :required => true
  key :adjectiveTwo, String, :required => true
  key :adjectiveThree, String, :required => true
  key :adverbOne, String, :required => true
  key :adverbTwo, String, :required => true
  key :adverbThree, String, :required => true
end

app/models/story.rb
class Story
  include MongoMapper::Document

  key :nounOne, String, :required => true, :required => true
  key :nounTwo, String, :required => true
  key :nounThree, String, :required => true
  key :nounFour, String, :required => true
  key :verbOne, String, :required => true
  key :verbTwo, String, :required => true
  key :verbThree, String, :required => true
  key :verbFour, String, :required => true
  key :verbFive, String, :required => true
  key :adjectiveOne, String, :required => true
  key :adjectiveTwo, String, :required => true
  key :adjectiveThree, String, :required => true
  key :adverbOne, String, :required => true
  key :adverbTwo, String, :required => true
  key :adverbThree, String, :required => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  before_action :set_example, only: [:show, :edit, :update, :destroy]

  # GET /examples
  # GET /examples.json
  def index
    @examples = Example.all
  end

  # GET /examples/1
  # GET /examples/1.json
  def show
    #lowercase
  end

  # GET /examples/new
  def new
    @example = Example.new
  end

  # GET /examples/1/edit
  def edit
  end

  # POST /examples
  # POST /examples.json
  def create
    @example = Example.new(example_params)

    respond_to do |format|
      if @example.save
        format.html { redirect_to @example, notice: 'Example was successfully created.' }
        format.json { render :show, status: :created, location: @example }
      else
        format.html { render :new }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /examples/1
  # PATCH/PUT /examples/1.json
  def update
    respond_to do |format|
      if @example.update(example_params)
        format.html { redirect_to @example, notice: 'Example was successfully updated.' }
        format.json { render :show, status: :ok, location: @example }
      else
        format.html { render :edit }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /examples/1
  # DELETE /examples/1.json
  def destroy
    @example.destroy
    respond_to do |format|
      format.html { redirect_to examples_url, notice: 'Example was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_example
      @example = Example.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def example_params
      params.require(:example).permit(:nounOne, :nounTwo, :nounThree, :nounFour, :verbOne, :verbTwo, :verbThree, :verbFour, :verbFive, :adjectiveOne, :adjectiveTwo, :adjectiveThree, :adverbOne, :adverbTwo, :adverbThree)
    end

    def lowercase
      #@example.each { |entry| entry.downcase! }
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def index
  	@stories = Story.all
  end

  def show
  	@story = Story.find(params[:id])
  end

  def new
  	@story = Story.new
  end

  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story generated.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
    def story_params 
      params.require(:form).permit(:nounOne, :nounTwo, :nounThree, :nounFour, :verbOne, :verbTwo, :verbThree, :verbFour, :verbFive, :adjectiveOne, :adjectiveTwo, :adjectiveThree, :adverbOne, :adverbTwo, :adverbThree)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/views/examples/_form.html.erb
<%= form_for(@example) do |f| %>
  <% if @example.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@example.errors.count, "error") %> prohibited this example from being saved:</h2>

      <ul>
      <% @example.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <strong>Plural Noun</strong><br>
    <%= f.text_field :nounOne %>
  </div>
  <div class="field">
    <strong>Plural Noun</strong><br>
    <%= f.text_field :nounTwo %>
  </div>
  <div class="field">
    <strong>Singular Noun</strong><br>
    <%= f.text_field :nounThree %>
  </div>
  <div class="field">
    <strong>Plural Noun</strong><br>
    <%= f.text_field :nounFour %>
  </div>
  <div class="field">
    <strong>Plural Verb (Present tense)</strong><br>
    <%= f.text_field :verbOne %>
  </div>
  <div class="field">
    <strong>Plural Verb (Present tense)</strong><br>
    <%= f.text_field :verbTwo %>
  </div>
  <div class="field">
    <strong>Infinitive Verb (the "to" is provided)</strong> <a href="#" data-toggle="modal" data-target="#myModal">What's that?</a><br>
    <%= f.text_field :verbThree %>
  </div>
  <div class="field">
    <strong>Infinitive Verb (the "to" is provided)</strong><br>
    <%= f.text_field :verbFour %>
  </div>
  <div class="field">
    <strong>Infinitive Verb (the "to" is provided)</strong><br>
    <%= f.text_field :verbFive %>
  </div>
  <div class="field">
    <strong>Adjective</strong><br>
    <%= f.text_field :adjectiveOne %>
  </div>
  <div class="field">
    <strong>Adjective</strong><br>
    <%= f.text_field :adjectiveTwo %>
  </div>
  <div class="field">
    <strong>Adjective</strong><br>
    <%= f.text_field :adjectiveThree %>
  </div>
  <div class="field">
    <strong>Adverb</strong><br>
    <%= f.text_field :adverbOne %>
  </div>
  <div class="field">
    <strong>Adverb</strong><br>
    <%= f.text_field :adverbTwo %>
  </div>
  <div class="field">
    <strong>Adverb</strong><br>
    <%= f.text_field :adverbThree %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/examples/edit.html.erb
<h1>Editing Example</h1>

<%= render 'form' %>

<%= link_to 'Show', @example %> |
<%= link_to 'Back', examples_path %>

app/views/examples/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Examples</h1>

<table>
  <thead>
    <tr>
      <th>Nounone</th>
      <th>Nountwo</th>
      <th>Nounthree</th>
      <th>Verbone</th>
      <th>Verbtwo</th>
      <th>Verbthree</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @examples.each do |example| %>
      <tr>
        <td><%= example.nounOne %></td>
        <td><%= example.nounTwo %></td>
        <td><%= example.nounThree %></td>
        <td><%= example.verbOne %></td>
        <td><%= example.verbTwo %></td>
        <td><%= example.verbThree %></td>
        <td><%= link_to 'Show', example %></td>
        <td><%= link_to 'Edit', edit_example_path(example) %></td>
        <td><%= link_to 'Destroy', example, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mad Lib', new_example_path %>

app/views/examples/new.html.erb
<h1>New Mad Lib</h1>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">What's an infinitive verb?</h4>
      </div>
      <div class="modal-body">
        <p>The infinitive form of a verb is usually preceded by to (e.g., to run, to dance, to think). The infinitive form is not always preceded by to. Look at these examples:</p>

        <p>I need to run every day. (The infinitive form with the word to is called the full infinitive or to-infinitive.)</p>


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<%= render 'form' %>

<%= link_to 'Back', examples_path %>

app/views/examples/show.html.erb
<h1 class="center">The Three Little Pigs</h1>

<div class="main-text">
  <p>Once upon a time, there were three <strong><%= @example.adjectiveOne %></strong> pigs. One day, their mother said, "You are all grown up and must <strong><%= @example.verbOne %></strong> on your own." So they left to <strong><%= @example.verbTwo %></strong> their houses.  The first little pig only wanted to work all day and quickly built his house out of <strong><%= @example.nounOne %></strong>.  The second little pig wanted to <strong><%= @example.verbThree %></strong> all day so he built his house with <strong><%= @example.nounTwo %></strong>. The third little pig knew that a wolf leved nearby and worked <strong><%= @example.adverbOne %></strong> to build his house out of <strong><%= @example.nounFour %></strong>. One day, the wolf knocked on the first pig's house and said, "Let me in or I'll <strong><%= @example.verbFour %></strong> your house down!" The pig didn't, so the wolf blew down the house. The wolf knocked on the second pig's <strong><%= @example.nounThree %></strong> and said, "Let me in or I'll <strong><%= @example.verbFive %></strong> your house down!" The pig didn't, so the wolf blew the house down. Finally, the wolf knocked <strong><%= @example.adverbTwo %></strong> on the third <strong><%= @example.adjectiveTwo %></strong> pig's door. He said, "Let me in or I'll blow your house down!" The pig didn't and the wolf huffed and puffed but could not blow the house down. The pigs went on to live <strong><%= @example.adverbThree %></strong> ever after.</p>
</div>
<h2 class="center">The End</h2>

<%= link_to 'Edit', edit_example_path(@example) %> |
<%= link_to 'Back', examples_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>MadLibs</title>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="main-content">
		<%= yield %>
	</div>
</body>
</html>

app/views/stories/_form.html.erb
<% form_for @story do |f| %>
	<%#= f.error_messages %>
	<div class="field">
		<p>
			<strong>Noun 1</strong><br />
			<%= f.text_field :nounOne %><br />
			<strong>Noun 2</strong><br />
			<%= f.text_field :nounTwo %><br />

		</p>
	</div>
<% end %>

app/views/stories/edit.html.erb
edit.html.erb

app/views/stories/index.html.erb
<h1>All Mad Libs</h1>

<%= link_to 'New Mad Lib', new_story_path %>

app/views/stories/new.html.erb
<h2>Fill in the blanks with the appropriate sentence component.</h2>

<%= render 'form' %>

app/views/stories/show.html.erb
<h1>Show</h1>